printf("===================================================================");
printf("||Position| N° voiture | Nbr Pitstop | Nbr tours |  Temps total  ||");
printf("===================================================================");
printf("||   01   |     %i     |     %i      |    %i     |   %f   ||", tabVoiture[0]->numVoiture, tabVoiture[0]->nbrPitstop, tabVoiture[0]->nbrTour, tabVoiture[0]->tempsActuel);
printf("-------------------------------------------------------------------");
printf("||   02   |     %i     |     %i      |    %i     |   %f   ||", tabVoiture[1]->numVoiture, tabVoiture[1]->nbrPitstop, tabVoiture[1]->nbrTour, tabVoiture[1]->tempsActuel);
printf("-------------------------------------------------------------------");
printf("||   03   |     %i     |     %i      |    %i     |   %f   ||", tabVoiture[2]->numVoiture, tabVoiture[2]->nbrPitstop, tabVoiture[2]->nbrTour, tabVoiture[2]->tempsActuel);
printf("-------------------------------------------------------------------");
printf("||   04   |     %i     |     %i      |    %i     |   %f   ||", tabVoiture[3]->numVoiture, tabVoiture[3]->nbrPitstop, tabVoiture[3]->nbrTour, tabVoiture[3]->tempsActuel);
printf("-------------------------------------------------------------------");
printf("||   05   |     %i     |     %i      |    %i     |   %f   ||", tabVoiture[4]->numVoiture, tabVoiture[4]->nbrPitstop, tabVoiture[4]->nbrTour, tabVoiture[4]->tempsActuel);
printf("-------------------------------------------------------------------");
printf("||   06   |     %i     |     %i      |    %i     |   %f   ||", tabVoiture[5]->numVoiture, tabVoiture[5]->nbrPitstop, tabVoiture[5]->nbrTour, tabVoiture[5]->tempsActuel);
printf("-------------------------------------------------------------------");
printf("||   07   |     %i     |     %i      |    %i     |   %f   ||", tabVoiture[6]->numVoiture, tabVoiture[6]->nbrPitstop, tabVoiture[6]->nbrTour, tabVoiture[6]->tempsActuel);
printf("-------------------------------------------------------------------");
printf("||   08   |     %i     |     %i      |    %i     |   %f   ||", tabVoiture[7]->numVoiture, tabVoiture[7]->nbrPitstop, tabVoiture[7]->nbrTour, tabVoiture[7]->tempsActuel);
printf("-------------------------------------------------------------------");
printf("||   09   |     %i     |     %i      |    %i     |   %f   ||", tabVoiture[8]->numVoiture, tabVoiture[8]->nbrPitstop, tabVoiture[8]->nbrTour, tabVoiture[8]->tempsActuel);
printf("-------------------------------------------------------------------");
printf("||   10   |     %i     |     %i      |    %i     |   %f   ||", tabVoiture[9]->numVoiture, tabVoiture[9]->nbrPitstop, tabVoiture[9]->nbrTour, tabVoiture[9]->tempsActuel);
printf("-------------------------------------------------------------------");
printf("||   11   |     %i     |     %i      |    %i     |   %f   ||", tabVoiture[10]->numVoiture, tabVoiture[10]->nbrPitstop, tabVoiture[10]->nbrTour, tabVoiture[10]->tempsActuel);
printf("-------------------------------------------------------------------");
printf("||   12   |     %i     |     %i      |    %i     |   %f   ||", tabVoiture[11]->numVoiture, tabVoiture[11]->nbrPitstop, tabVoiture[11]->nbrTour, tabVoiture[11]->tempsActuel);
printf("-------------------------------------------------------------------");
printf("||   13   |     %i     |     %i      |    %i     |   %f   ||", tabVoiture[12]->numVoiture, tabVoiture[12]->nbrPitstop, tabVoiture[12]->nbrTour, tabVoiture[12]->tempsActuel);
printf("-------------------------------------------------------------------");
printf("||   14   |     %i     |     %i      |    %i     |   %f   ||", tabVoiture[13]->numVoiture, tabVoiture[13]->nbrPitstop, tabVoiture[13]->nbrTour, tabVoiture[13]->tempsActuel);
printf("-------------------------------------------------------------------");
printf("||   15   |     %i     |     %i      |    %i     |   %f   ||", tabVoiture[14]->numVoiture, tabVoiture[14]->nbrPitstop, tabVoiture[14]->nbrTour, tabVoiture[14]->tempsActuel);
printf("-------------------------------------------------------------------");
printf("||   16   |     %i     |     %i      |    %i     |   %f   ||", tabVoiture[15]->numVoiture, tabVoiture[15]->nbrPitstop, tabVoiture[15]->nbrTour, tabVoiture[15]->tempsActuel);
printf("-------------------------------------------------------------------");
printf("||   17   |     %i     |     %i      |    %i     |   %f   ||", tabVoiture[16]->numVoiture, tabVoiture[16]->nbrPitstop, tabVoiture[16]->nbrTour, tabVoiture[16]->tempsActuel);
printf("-------------------------------------------------------------------");
printf("||   18   |     %i     |     %i      |    %i     |   %f   ||", tabVoiture[17]->numVoiture, tabVoiture[17]->nbrPitstop, tabVoiture[17]->nbrTour, tabVoiture[17]->tempsActuel);
printf("-------------------------------------------------------------------");
printf("||   19   |     %i     |     %i      |    %i     |   %f   ||", tabVoiture[18]->numVoiture, tabVoiture[18]->nbrPitstop, tabVoiture[18]->nbrTour, tabVoiture[18]->tempsActuel);
printf("-------------------------------------------------------------------");
printf("||   20   |     %i     |     %i      |    %i     |   %f   ||", tabVoiture[19]->numVoiture, tabVoiture[19]->nbrPitstop, tabVoiture[19]->nbrTour, tabVoiture[19]->tempsActuel);
printf("===================================================================");
printf("Meilleur temps essais :%f                                  ||", meilleurTourEssai);
printf("Meilleur temps qualif :%f                                  ||", meilleurTourQualif);
printf("Meilleur temps course :%f                                  ||", meilleurTourCourse);
printf("-------------------------------------------------------------------");
printf("Meilleur temps secteur 1 :%f                               ||", meilleurSecteur1);
printf("Meilleur temps secteur 2 :%f                               ||", meilleurSecteur2);
printf("Meilleur temps secteur 3 :%f                               ||", meilleurSecteur3);
printf("===================================================================");
